stages:
  - build
  - test

build:
  stage: build
  only:
    - dev
  cache:
    paths:
      - dist
  before_script:
    - echo 'build starts'
    - sudo apt-get update
    - sudo apt-get install npm -y
    - npm --version
    - npm install

  script:
    - npm run build
  artifacts:
    paths:
      - ./build
  tags:
    - react
