stages:
  - build
  - test

job_build:
  image: node:latest
  stage: build
  before_script:
    - echo 'build starts'
    - sudo apt-get update -qy
    - apt-get install --no-install-recommends -y npm
    - npm --version
    - npx --version
    - gem install dpl
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - ./build

job_test:
  stage: test
  script:
    - echo "Running tests"
