stages:
  - build
  - test

job_build:
  image: node:latest
  stage: build
  before_script:
    - echo 'build starts'
  script:
    - pwd
    - npm run build
  artifacts:
    paths:
      - ./build

job_test:
  stage: test
  script:
    - echo "Running tests"
