stages:
  - libs
  - build
  - test

npm:
  stage: libs
  only:
    - dev
  cache:
    paths:
      - node_modules
  script:
    - npm install

build:
  stage: build
  only:
    - dev
  cache:
    paths:
      - dist
  before_script:
    - echo 'build starts'
  script:
    - npm run build
  artifacts:
    paths:
      - ./build
  tags:
    - react
